# Generated by Django 5.2.7 on 2025-10-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=4)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_dept', models.CharField(max_length=100)),
            ],
        ),
    ]
